apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: sasidhar299/testwebapp:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
